version: '2'
services:
  fpm:
    build: .
    container_name: classificators_fpm
    env_file: ".env"
    depends_on:
      - db
    volumes:
      - ".:/var/www/html"
  nginx:
    build: ./docker/nginx
    container_name: classificators_nginx
    depends_on:
      - fpm
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ".:/var/www/html"
  db:
    build: ./docker/db
    container_name: classificators_db
    ports:
      - "${DB_HOST_PORT}:3306"
    volumes:
      - "${DB_DATA_VOLUME}:/var/lib/mysql"
    environment:
     MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
     MYSQL_USER: ${DB_USER}
     MYSQL_PASSWORD: ${DB_PASS}
     MYSQL_DATABASE: ${DB_NAME}